            - name: Sematext Synthetics CI/CD
  # You may pin to the exact commit or the version.
  # uses: sematext/synthetics-cicd@10cc8690741528168090864c322d47f1c885073d
  uses: sematext/synthetics-cicd@v1.0.1
  with:
    # The ID of the monitor group to run the tests against (example: 42)
    MONITOR_GROUP_ID: 
    # The region where your Sematext Cloud account is located ('EU' or 'US')
    REGION: 
    # Your Sematext Cloud account's API key (visible in Settings -> API)
    SEMATEXT_API_KEY: 
    # The URL to run the Synthetics tests against (optional, will use the URL specified in the Sematext Cloud UI if not provided)
    TARGET_URL: # optional
    # The commit hash that the Synthetics tests will be triggered for (optional and used for repository dispatches which aren't directly linked to a commit, will use the commit hash of the current commit if not provided)
    GIT_COMMIT_HASH: # optional
    # Whether to use the HEAD SHA for the Synthetics tests (optional, defaults to false)
    USE_HEAD_SHA: # optional
          
